#' @title tweet_db
#' @name tweet_db
#' @docType data
#' @description A data.frame holding the relevant data for the tweet database. Built by \code{\link{addNewTweetToDB}}, and used by \code{\link{getTweetByID}} and \code{\link{getTweetByCategory}}. 
#' @param tweet_text The tweet text. 
#' @param category The category of tweet. 
#' @param media_path Optional. The path to any media/pictures you want to tweet with it.
#' @param id An automatically generated unique identifier in your \code{\link{tweet_db}}, as generated by \code{\link{addNewTweetToDB}}.
#' @examples 
#' tweet_db <- addNewTweetToDB("I like cats"     , category="animals")
#' tweet_db <- addNewTweetToDB("I like dogs too.", category="animals", tweet_db = tweet_db)
#' tweet_db <- addNewTweetToDB("I don't like sardines.", category="food", tweet_db = tweet_db)
#' tweet_db
NULL
